# Generated by Django 5.1.2 on 2024-10-30 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brrrgrrr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomBurgerIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('custom_burger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brrrgrrr.customburger')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brrrgrrr.ingredient')),
            ],
        ),
        migrations.AlterField(
            model_name='customburger',
            name='ingredients',
            field=models.ManyToManyField(through='brrrgrrr.CustomBurgerIngredient', to='brrrgrrr.ingredient'),
        ),
    ]
