# Generated by Django 5.1.2 on 2024-11-02 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brrrgrrr', '0002_alter_ingredient_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
