# Generated by Django 5.1.2 on 2024-10-30 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brrrgrrr', '0002_customburgeringredient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customburger',
            name='ingredients',
            field=models.ManyToManyField(related_name='custom_burgers', through='brrrgrrr.CustomBurgerIngredient', to='brrrgrrr.ingredient'),
        ),
    ]
