# Generated by Django 5.1.2 on 2024-11-02 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brrrgrrr', '0003_alter_ingredient_is_available'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
