# Generated by Django 5.1.2 on 2024-10-30 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brrrgrrr', '0004_remove_customburger_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='customburger',
            name='ingredients',
            field=models.ManyToManyField(related_name='custom_burgers', through='brrrgrrr.CustomBurgerIngredient', to='brrrgrrr.ingredient'),
        ),
    ]
